version: "3.8"

services:
  node-app:
    build: .
    container_name: pos-nodejs-app
    ports:
      - "5002:5002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
