version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-nodejs-backend-app
    ports:
      - "5000:5000"
    volumes:
      - .:/home/app
    working_dir: /home/app
    environment:
      - NODE_ENV=production
